school/classroom/urls.py
from django.urls import path
from .views import (HomeView, ThankYou, ContactFormView, TeacherCreateView, TeacherListView)

app_name = 'classroom'

#domain.com/classroom
urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('thank_you/', ThankYou.as_view(), name="thankyou"),
    path("contact/", ContactFormView.as_view(), name='contact'),
    path("teacher/", TeacherCreateView.as_view(), name='teacher'),
    path("teacherlist/", TeacherListView.as_view(), name="teacherlist"),

]

school/school/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('classroom/', include('classroom.urls')),
    
]

school/classroom/models.py
from django.db import models

# Create your models here.

class Teacher(models.Model):
    first_name = models.CharField(max_length=40)
    last_name = models.CharField(max_length=40)
    subject = models.CharField(max_length=40)


    def __str__(self) -> str:
        return f"{self.first_name} {self.last_name} teaches {self.last_name}"

school/classroom/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField()
    message = forms.CharField(widget=forms.Textarea)

school/classroom/views.py
from django.shortcuts import render
from django.views.generic import (TemplateView, FormView, CreateView, ListView,DetailView)
from classroom.models import Teacher
from django.urls import reverse, reverse_lazy

from classroom.forms import ContactForm

# Create your views here.

# def myHome(request):
#     return render(request, 'classroom/home.html')


class HomeView(TemplateView):
    template_name = 'classroom/home.html'

class ThankYou(TemplateView):
    template_name = 'classroom/thank_you.html'



class TeacherCreateView(CreateView):
    model = Teacher

    #modef_form.html

    fields = "__all__"
    success_url = reverse_lazy("classroom:thankyou")


class TeacherListView(ListView):
    #model_list.html
    model = Teacher

    queryset = Teacher.objects.order_by("first_name")

    context_object_name = "teacher_list"
    

class TeacherDetailView(DetailView):
    # model_detail.html
    model = Teacher
    #pk --> {{teacher}}


class ContactFormView(FormView):
    form_class = ContactForm
    template_name = "classroom/contact.html"

    #this is not a template.html
    success_url = reverse_lazy("classroom:thankyou")

    #success url
    #what to do with form?

    def form_valid(self, form):
        print(form.cleaned_data)

        #form.save
        return super().form_valid(form)
    

school/classroom/templates/classroom/contact.html
<h1>Form View Template (contact.html)</h1>

<form method="POST">
    {% csrf_token %}

    {{ form.as_p}}
    <input type="submit" value="Submit">
</form>

school/classroom/templates/classroom/home.html
<h1>Welcome to home.html</h1>

<ul>

    <li>
        <a href="{% url "classroom:thankyou" %}">Thank you page link</a>
    </li>

    <li>
        <a href="{% url "classroom:contact" %}">Contact Form page link</a>
    </li>

    <li>
        <a href="{% url "classroom:teacher" %}">Teacher Form page link</a>
    </li>

    <li>
        <a href="{% url "classroom:teacherlist" %}">Teacher list page link</a>
    </li>

</ul>

school/classroom/templates/classroom/teacher_detail.html
<h1>

    Detail View for a Teacher

</h1>

{{teacher}}

school/classroom/templates/classroom/teacher_form.html
<h1>

    Teacher Form

</h1>

<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Submit">

</form>

school/classroom/templates/classroom/teacher_list.html
<h1>
    List of all teachers
</h1>

<ul>

    {% for teacher in teacher_list %}
    
        <li>
            {{teacher.first_name}} {{teacher.last_name}}, {{teacher.subject}}
        </li>

    {% endfor %}

</ul>

school/classroom/templates/classroom/thank_you.html
<h1>Thank you</h1>